workflows:
  ios-build:
    name: iOS Build

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - cd ios && xcodebuild CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app