// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9leI7lguB-_TCeM4CGNvTKA68KmP9KX8',
    appId: '1:279825670275:web:ec348ecd358291ee3c7bb6',
    messagingSenderId: '279825670275',
    projectId: 'scrptaty',
    authDomain: 'scrptaty.firebaseapp.com',
    storageBucket: 'scrptaty.firebasestorage.app',
    measurementId: 'G-B24EBD6S74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0DSdjGIW3SwYne40M9jx2HIWEJ1ggrYw',
    appId: '1:279825670275:android:bb3de20098b9892c3c7bb6',
    messagingSenderId: '279825670275',
    projectId: 'scrptaty',
    storageBucket: 'scrptaty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSJSm3DWDgd_0vqyq81tMeKfdRykUJ3k',
    appId: '1:279825670275:ios:59cfa19a9d2810253c7bb6',
    messagingSenderId: '279825670275',
    projectId: 'scrptaty',
    storageBucket: 'scrptaty.firebasestorage.app',
    iosClientId: '279825670275-8ef1doej7etpgjohqcoceettaf2vngb6.apps.googleusercontent.com',
    iosBundleId: 'com.scrptaty.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSJSm3DWDgd_0vqyq81tMeKfdRykUJ3k',
    appId: '1:279825670275:ios:8f690c88735224783c7bb6',
    messagingSenderId: '279825670275',
    projectId: 'scrptaty',
    storageBucket: 'scrptaty.firebasestorage.app',
    iosClientId: '279825670275-vsgr6j9pman4jqollm90lub8m8a1li8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9leI7lguB-_TCeM4CGNvTKA68KmP9KX8',
    appId: '1:279825670275:web:f0706f11d537e9683c7bb6',
    messagingSenderId: '279825670275',
    projectId: 'scrptaty',
    authDomain: 'scrptaty.firebaseapp.com',
    storageBucket: 'scrptaty.firebasestorage.app',
    measurementId: 'G-0JVS12WXL9',
  );
}
