platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously in Ruby 3.x,
# which causes builds to fail. Disabling analytics to avoid this issue.
install! 'cocoapods',
         deterministic_uuids: false,
         code_signing_disabled: true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_13_targets(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end